### ISSUE TITLE
Could not mount filesystem: Mount process has terminated unexpectedly.

### ISSUE THREAD

**Issue by castus** [mgorbach/macfusion2#31]
Hey guys,
I have this error when I'm try to connect with SSH: Could not mount filesystem: Mount process has terminated unexpectedly.

In terminal, when I'm trying to connect to ssh it works, but with MacFusion it won't work.

This is log messages:

(SSHServerFS, Ravage, 16.07.2012 16:39) debug1: Server accepts key: pkalg ssh-rsa blen 276
(SSHServerFS, Ravage, 16.07.2012 16:39) debug1: Authentication succeeded (publickey).
Authenticated to ##server-name.
debug1: channel 0: new [client-session]
debug1: Requesting no-more-sessions@openssh.com
debug1: Entering interactive session.
(SSHServerFS, Ravage, 16.07.2012 16:39) debug1: Sending environment.
debug1: Sending subsystem: sftp
(SSHServerFS, Ravage, 16.07.2012 16:39) volicon: failed to access volume icon file (2)
(MFClient, Ravage, 16.07.2012 16:39) Note status changed for fs <MFClientFS: 0x400440ac0> (Ravage) to Failed to Mount
(SSHServerFS, Ravage, 16.07.2012 16:39) mount_fusefs: failed to mount /Volumes/Ravage@/dev/fuse0: Socket is not connected
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug1: channel 0: free: client-session, nchannels 1
debug1: fd 0 clearing O_NONBLOCK
debug1: fd 2 clearing O_NONBLOCK
Transferred: sent 2800, received 2424 bytes, in 0.2 seconds
Bytes per second: sent 12535.7, received 10852.3
debug1: Exit status 0

**Comment by bowmasters** [comment]
I had this issue too and found this in the console log:

_Library not loaded: /usr/local/lib/libfuse.0.dylib
...
Reason: image not found_

Check if you see this error in your logs. If so you'll need to get the latest macfuse from tuxera (not the one from the google code macfuse project as it seems to be unmaintained and, if you're on [mountain] lion, is the wrong architecture) and it will install the libfuse.0.dylib in the correct location.

http://www.tuxera.com/mac/macfuse-core-10.5-2.1.9.dmg

Hope this fixes your issue

**Comment by clslrns** [comment]
Thanks, @bowmasters, it helps me.

**Comment by brunovenceslau** [comment]
Thank you @bowmasters. It helped me as well.

**Comment by dechov** [comment]
Yes. Thanks @bowmasters

**Comment by teet** [comment]
Thanks. works now

**Comment by x128** [comment]
Thanks @bowmasters!

**Comment by dreasysnail** [comment]
Thank you @bowmasters

**Comment by nicopixeldev** [comment]
I love you @bowmasters!!

**Comment by Glideh** [comment]
Thx @bowmasters it brung me to the next error...

**Comment by shalmalisohoni** [comment]
Fixed it for me too! Thanks!

**Comment by 0xbepresent** [comment]
Works perfect ;)

**Comment by nullzero** [comment]
Thank you!

**Comment by AskBre** [comment]
Cheers! Fixed it for me.

**Comment by klimaj** [comment]
Genius.

**Comment by castus** [comment]
It works, thanks ! :)

**Comment by lareguna** [comment]
Wonderful !! Works for me now !!

**Comment by zgr0629** [comment]
Thank you, but why not put this link at http://macfusionapp.org/ frontpage instead the google code link

**Comment by bowmasters** [comment]
Try reaching out to the macfusion team and see if they'll update the homepage (I'm just a passer by, not at all affiliated with the project)

**Comment by cryptowest** [comment]
Thanks, helped me also.

**Comment by jherder** [comment]
Worked for me too!

**Comment by KarimGeiger** [comment]
Dito. Looks like this project is dead, huh? :(

**Comment by chris-stg** [comment]
If you are using OSXFuse, installing the Macfuse compatibility layer will solve this problem as well.

**Comment by LimeBlast** [comment]
What @chris-stg said worked for me.
